image: barbem/risc-v_cep
stages:
  - test

kernel_tests:
     stage: test
     script:
        - cd src
        - timeout 3m make go > report.txt || true
        - cat report.txt
        - if grep -q "ERROR" report.txt || ! grep -q "TESTS REPORT END" report.txt; then
            exit 1;
          fi
