image: barbem/risc-v_cep
stages:
  - test

kernel_tests:
     stage: test
     script:
        - set +e
        - cd src
        - timeout 3m make go > report.txt || true
        - grep -q "ERROR" report.txt
        - if [ $? -eq 0 ]; then exit 1; fi
        - grep -q "TESTS REPORT END" report.txt
        - if [ $? -ne 0 ]; then exit 1; fi
        - set -e
