diff a/src/user/Makefile b/src/user/Makefile	(rejected hunks)
@@ -80,7 +80,7 @@ include build/apps.mk
 #
 
 TESTS_DIR     := tests
-TESTS_OPTIONS := CONS_READ_LINE WITH_MSG USER_SPACE
+TESTS_OPTIONS := WITH_MSG USER_SPACE
 include build/tests.mk
 
 #
